/* ============ MU CHART DATA ============ */
export const MU_CORE = [
  ["Radiohead","Kid A"],
  ["My Bloody Valentine","Loveless"],
  ["Animal Collective","Merriweather Post Pavilion"],
  ["Talking Heads","Remain in Light"],
  ["Slint","Spiderland"],
  ["King Crimson","In the Court of the Crimson King"],
  ["Godspeed You! Black Emperor","Lift Your Skinny Fists Like Antennas to Heaven"],
  ["Kanye West","My Beautiful Dark Twisted Fantasy"],
  ["Death Grips","The Money Store"],
  ["American Football","American Football"],
  ["Captain Beefheart & His Magic Band","Trout Mask Replica"],
  ["Swans","Soundtracks For The Blind"],
  ["The Beach Boys","Pet Sounds"],
  ["The Velvet Underground","The Velvet Underground & Nico"]
];

export const MU_SECTIONS = {
  A: [
    ["Radiohead","OK Computer"],
    ["Radiohead","In Rainbows"],
    ["Have a Nice Life","Deathconsciousness"],
    ["Sigur Rós","Ágætis Byrjun"],
    ["Godspeed You! Black Emperor","F# A# ∞"],
    ["Talk Talk","Laughing Stock"],
    ["Slowdive","Souvlaki"],
    ["Björk","Homogenic"],
    ["Nirvana","Nevermind"],
    ["Nirvana","In Utero"],
    ["Elliott Smith","Either/Or"],
    ["Jeff Buckley","Grace"]
  ],
  B: [
    ["The Smashing Pumpkins","Siamese Dream"],
    ["Pavement","Slanted & Enchanted"],
    ["Grimes","Visions"],
    ["The Flaming Lips","The Soft Bulletin"],
    ["Modest Mouse","The Lonesome Crowded West"],
    ["Modest Mouse","The Moon & Antarctica"],
    ["Weezer","Weezer"],
    ["Weezer","Pinkerton"],
    ["Nine Inch Nails","The Downward Spiral"],
    ["Xiu Xiu","A Promise"],
    ["Built to Spill","Perfect From Now On"],
    ["Les Rallizes Dénudés","'77 Live"]
  ],
  C: [
    ["Yo La Tengo","I Can Hear the Heart Beating as One"],
    ["The Magnetic Fields","69 Love Songs"],
    ["Fugazi","Repeater"],
    ["Cardiacs","Sing to God"],
    ["Red House Painters","Down Colorful Hill"],
    ["Codeine","Frigid Stars"],
    ["Spiritualized","Ladies and Gentlemen We Are Floating in Space"],
    ["Low","I Could Live in Hope"],
    ["Macintosh Plus","Floral Shoppe"],
    ["Duster","Stratosphere"],
    ["Lisa Germano","Geek the Girl"],
    ["Giles Corey","Giles Corey"]
  ],
  D: [
    ["Royal Trux","Twin Infinitives"],
    ["At the Drive-In","Relationship of Command"],
    ["Drive Like Jehu","Yank Crime"],
    ["Unwound","Leaves Turn Inside You"],
    ["Cap'n Jazz","Analphabetapolothology"],
    ["Beck","Sea Change"],
    ["Jim O'Rourke","Eureka"],
    ["James Blake","James Blake"],
    ["The Dismemberment Plan","Emergency & I"],
    ["Sweet Trip","Velocity : Design : Comfort"],
    ["Brand New","The Devil and God Are Raging Inside Me"],
    ["Portishead","Dummy"]
  ],
  E: [
    ["Death Grips","Exmilitary"],
    ["Death Grips","No Love Deep Web"],
    ["Joanna Newsom","Ys"],
    ["Joanna Newsom","Have One on Me"],
    ["The Strokes","Is This It"],
    ["Candy Claws","Ceres & Calypso in the Deep Time"],
    ["Tim Hecker","Ravedeath, 1972"],
    ["The Microphones","The Glow, Pt. 2"],
    ["They Might Be Giants","Flood"],
    ["Tame Impala","Lonerism"],
    ["Sufjan Stevens","Illinois"],
    ["Sufjan Stevens","The Age of Adz"]
  ],
  F: [
    ["Sun Kil Moon","Benji"],
    ["Tortoise","Millions Now Living Will Never Die"],
    ["Arcade Fire","Funeral"],
    ["The Avalanches","Since I Left You"],
    ["Gorillaz","Demon Days"],
    ["Mac DeMarco","Salad Days"],
    ["Mercury Rev","Yerself Is Steam"],
    ["Don Caballero","What Burns Never Returns"],
    ["The Jesus Lizard","Goat"],
    ["The Mars Volta","De-Loused in the Comatorium"],
    ["Coil","The Ape of Naples"],
    ["LCD Soundsystem","Sound Of Silver"]
  ],
  G: [
    ["Swans","The Seer"],
    ["Swans","To Be Kind"],
    ["Fishmans","Long Season"],
    ["Boredoms","Vision Creation Newsun"],
    ["Interpol","Turn on the Bright Lights"],
    ["Fleet Foxes","Fleet Foxes"],
    ["Nick Cave & The Bad Seeds","Let Love In"],
    ["Dean Blunt","The Redeemer"],
    ["The Antlers","Hospice"],
    ["Kanye West","Yeezus"],
    ["The Olivia Tremor Control","Black Foliage: Animation Music"],
    ["Ween","The Mollusk"]
  ],
  H: [
    ["Panda Bear","Person Pitch"],
    ["The Beach Boys","The SMiLE Sessions"],
    ["Belle and Sebastian","If You're Feeling Sinister"],
    ["Animal Collective","Spirit They're Gone, Spirit They've Vanished"],
    ["Animal Collective","Sung Tongs"],
    ["Animal Collective","Strawberry Jam"],
    ["Queens of the Stone Age","Songs for the Deaf"],
    ["Stars of the Lid","The Tired Sounds of Stars of the Lid"],
    ["Car Seat Headrest","Twin Fantasy"],
    ["Mr. Bungle","California"],
    ["Ride","Nowhere"],
    ["Stereolab","Transient Random-Noise Bursts with Announcements"]
  ]
};

export const MU_CLASSICS_SECTIONS = {
  A: [
    ["The Velvet Underground","Loaded"],
    ["The Velvet Underground","The Velvet Underground"],
    ["The Velvet Underground","White Light/White Heat"],
    ["Paul McCartney","Ram"],
    ["The Doors","The Doors"],
    ["Tom Waits","Rain Dogs"],
    ["The Rolling Stones","Exile on Main St."],
    ["The Beatles","Revolver"],
    ["The Beatles","Abbey Road"],
    ["The Beatles","Sgt. Pepper's Lonely Hearts Club Band"],
    ["Love","Forever Changes"],
    ["Leonard Cohen","Songs of Leonard Cohen"]
  ],
  B: [
    ["The Kinks","The Kinks Are the Village Green Preservation Society"],
    ["Yes","Close to the Edge"],
    ["Marvin Gaye","What's Going On"],
    ["Tim Buckley","Lorca"],
    ["Tim Buckley","Starsailor"],
    ["Tears for Fears","Songs from the Big Chair"],
    ["The United States of America","The United States of America"],
    ["Pink Floyd","The Piper at the Gates of Dawn"],
    ["Pink Floyd","The Dark Side of The Moon"],
    ["Pink Floyd","Wish You Were Here"],
    ["Wire","Pink Flag"],
    ["The Beach Boys","Surf's Up"]
  ],
  C: [
    ["Talking Heads","Fear of Music"],
    ["Joy Division","Unknown Pleasures"],
    ["Joy Division","Closer"],
    ["New Order","Power, Corruption & Lies"],
    ["The Gun Club","Fire of Love"],
    ["Lou Reed","Transformer"],
    ["Iggy Pop","Lust For Life"],
    ["The Stooges","Fun House"],
    ["Swans","Filth"],
    ["Swans","Children of God"],
    ["Dinosaur Jr.","You're Living All Over Me"],
    ["Einstürzende Neubauten","Halber Mensch"]
  ],
  D: [
    ["Foetus","Nail"],
    ["The Cure","Disintegration"],
    ["Jefferson Airplane","Volunteers"],
    ["Neil Young","After the Gold Rush"],
    ["Pere Ubu","The Modern Dance"],
    ["The Pop Group","Y"],
    ["Gang of Four","Entertainment!"],
    ["Lizzy Mercier Descloux","Press Color"],
    ["Sonic Youth","Daydream Nation"],
    ["Sonic Youth","Sister"],
    ["Sonic Youth","EVOL"],
    ["Various Artists","No New York"]
  ],
  E: [
    ["King Crimson","Discipline"],
    ["King Crimson","Larks' Tongues in Aspic"],
    ["King Crimson","Red"],
    ["This Heat","Deceit"],
    ["David Bowie","Low"],
    ["David Bowie","The Rise and Fall of Ziggy Stardust and the Spiders..."],
    ["Jackson C. Frank","Jackson C. Frank"],
    ["The Smiths","The Queen Is Dead"],
    ["John Fahey","Fare Forward Voyagers (Soldier's Choice)"],
    ["Comus","First Utterance"],
    ["Exuma","Exuma"],
    ["Os Mutantes","Os Mutantes"]
  ],
  F: [
    ["Devo","Q: Are We Not Men? A: We Are Devo!"],
    ["Coil","Horse Rotorvator"],
    ["Throbbing Gristle","20 Jazz Funk Greats"],
    ["Henry Cow","In Praise of Learning"],
    ["Talk Talk","Spirit of Eden"],
    ["Soft Machine","Third"],
    ["MC5","Kick Out the Jams"],
    ["Captain Beefheart & His Magic Band","Safe As Milk"],
    ["The Residents","Not Available"],
    ["Can","Tago Mago"],
    ["Can","Future Days"],
    ["Daniel Johnston","Hi, How Are You"]
  ],
  G: [
    ["Black Flag","Damaged"],
    ["Minor Threat","Complete Discography"],
    ["Bad Brains","Bad Brains"],
    ["R.E.M.","Murmur"],
    ["Madness","One Step Beyond"],
    ["Cocteau Twins","Treasure"],
    ["Hüsker Dü","Zen Arcade"],
    ["Minutemen","Double Nickels on the Dime"],
    ["Led Zeppelin","Led Zeppelin IV"],
    ["My Bloody Valentine","You Made Me Realise"],
    ["My Bloody Valentine","Isn't Anything"],
    ["Steely Dan","Aja"]
  ],
  H: [
    ["Glenn Branca","The Ascension"],
    ["Brian Eno","Another Green World"],
    ["Nick Cave & The Bad Seeds","Tender Prey"],
    ["Television","Marquee Moon"],
    ["Neu!","Neu!"],
    ["Popol Vuh","Hosianna Mantra"],
    ["Funkadelic","Maggot Brain"],
    ["The Who","Who's Next"],
    ["Faust","Faust"],
    ["Robert Wyatt","Rock Bottom"],
    ["Kate Bush","Hounds of Love"],
    ["Butthole Surfers","Psychic... Powerless... Another Man's Sac"]
  ],
  I: [
    ["Bob Dylan","Blonde on Blonde"],
    ["Bob Dylan","Blood on the Tracks"],
    ["Galaxie 500","On Fire"],
    ["Violent Femmes","Violent Femmes"],
    ["Amon Düül II","Yeti"],
    ["The Zombies","Odessey and Oracle"],
    ["Prince","Purple Rain"],
    ["Fleetwood Mac","Rumours"],
    ["The Jesus and Mary Chain","Psychocandy"],
    ["Public Image Ltd.","Second Edition"],
    ["The Red Krayola","The Parable of Arable Land"],
    ["Suicide","Suicide"]
  ],
  J: [
    ["Syd Barrett","The Madcap Laughs"],
    ["Frank Zappa","Hot Rats"],
    ["Frank Zappa","Freak Out!"],
    ["Jimi Hendrix","Are You Experienced?"],
    ["Pixies","Doolittle"],
    ["Pixies","Surfer Rosa"],
    ["Curtis Mayfield","Superfly"],
    ["The Replacements","Let It Be"],
    ["Big Black","Songs About Fucking"],
    ["Beat Happening","Beat Happening"],
    ["Genesis","Selling England by the Pound"],
    ["Elvis Presley","Elvis Presley"]
  ],
  K: [
    ["Mission of Burma","Vs."],
    ["Dead Kennedys","Fresh Fruit for Rotting Vegetables"],
    ["Chrome","Half Machine Lip Moves"],
    ["The Stone Roses","The Stone Roses"],
    ["Bruce Springsteen","Born to Run"],
    ["Nick Drake","Pink Moon"],
    ["Nick Drake","Bryter Layter"],
    ["Van Morrison","Astral Weeks"],
    ["The Clash","London Calling"],
    ["Nico","Desertshore"],
    ["Grateful Dead","American Beauty"],
    ["Van Dyke Parks","Song Cycle"]
  ]
};

